name: Windows 2022 RDP by Ngrok

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-2022
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin "Password123!"

      - name: Download ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath "$env:USERPROFILE\ngrok"

      - name: Connect ngrok (RDP)
        run: |
          $NGROK_AUTH_TOKEN = "${{ secrets.NGROK_AUTH }}"
          & "$env:USERPROFILE\ngrok\ngrok.exe" authtoken $NGROK_AUTH_TOKEN
          Start-Process "$env:USERPROFILE\ngrok\ngrok.exe" "tcp 3389"
          ping -n 99999 localhost
